### ISSUE TITLE
does it support metric depth estimation and training?

### ISSUE THREAD

**Issue by Zhefan-Xu** [scepter914/DepthAnything-ROS#1]
Thanks for sharing this excellent project. Since I want to deploy in real-world robot, is it able to perform metric depth estimation?

**Comment by scepter914** [comment]
@Zhefan-Xu

Thank you for your interest to my project.
I guess "metric depth estimation" means [this](https://github.com/LiheYoung/Depth-Anything/tree/main/metric_depth), and for my answer, it doesn't perform for now.
This project uses [this library](https://github.com/daniel89710/trt-depth-anything), and I expect it doesn't support metric depth.
However, because I guess the difference between the pre-train model and metric depth model is relative or absolute for output, it may perform by changing for

- [normalization for output](https://github.com/scepter914/DepthAnything-ROS/blob/main/src/tensorrt_depth_anything/tensorrt_depth_anything.cpp#L321)
- [conversion to msg data](https://github.com/scepter914/DepthAnything-ROS/blob/main/src/depth_anything_node/depth_anything_node.cpp#L113)

PR is welcome and if you notice anything for know-how, please feel free to let me know.

**Comment by Zhefan-Xu** [comment]
Thanks for the info. Yes, it seems like it currently only support for relative depth. I will look into how to apply metric depth.

**Comment by xiaobh1519** [comment]
> Thanks for the info. Yes, it seems like it currently only support for relative depth. I will look into how to apply metric depth.
Have you worked it out？I'm woking on it, but I met lots of problems...
